package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
)

// defaultConfigContent is written by `config init`.
// Every option includes its CLI flag and env var documented inline.
const defaultConfigContent = `# envsecrets configuration file
# Generated by: envsecrets config init
#
# Precedence (highest to lowest):
#   1. Command-line flags    (e.g. --vault)
#   2. Environment variables (e.g. ENVSECRETS_VAULT)
#   3. This config file
#   4. Built-in defaults

# 1Password vault name.
# CLI flag:        --vault <name>
# Environment var: ENVSECRETS_VAULT
vault = "Private"

# Default template file path for the gen-env command.
# CLI flag:        --template <path>
# Environment var: ENVSECRETS_TEMPLATE
template = ".env.tpl"

# Default output file path for the gen-env command.
# CLI flag:        --output <path>
# Environment var: ENVSECRETS_OUTPUT
output = ".env"
`

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Write a config file with defaults and documentation",
	Long: `Write the envsecrets config file populated with default values and
inline documentation. Exits with an error if the file already exists.

The file is written to ~/.config/envsecrets.toml by default.
Override the location with --config or $ENVSECRETS_CONFIG.`,
	Args: cobra.NoArgs,
	RunE: func(cmd *cobra.Command, args []string) error {
		path := configFilePath()

		if _, err := os.Stat(path); err == nil {
			return fmt.Errorf("config file already exists: %s — delete it first or edit it manually", path)
		}

		if err := os.WriteFile(path, []byte(defaultConfigContent), 0o600); err != nil {
			return fmt.Errorf("writing config file %q: %w", path, err)
		}

		_, _ = fmt.Fprintf(os.Stdout, "✓ config file written: %s\n", path)
		return nil
	},
}

func init() {
	configCmd.AddCommand(configInitCmd)
}
